### ISSUE TITLE
Add Share button to Product Card component

### ISSUE THREAD

**Issue by kappanjoe** [OriOri-CCP7/oriori#102]
- [x] Create a share button component
- [x] Add the share button to Product Card component
  - This may impact or be impacted by #110
- [x] After tapping the share button, users should be able to copy a link to the product
  - [x] Bonus: automatically copy the link for them
  - [x] Bonus: trigger the device's native share sheet function

**Comment by SirrorsMoore1975** [comment]
By executing navigator.share, for modern device, it would trigger the device native share sheet function. But if failed, it would trigger clipboard the share url, this is true on my Ubuntu machine.
