### ISSUE TITLE
Sort products by most recent availability

### ISSUE THREAD

**Issue by kappanjoe** [OriOri-CCP7/oriori#123]
Products listed in the following views should be sorted from **most recently available** to **least recently available**, followed by those that are **no longer available**:
- [x] Home
- [x] Bookmarks
- [x] Tried products
- [x] Search

### Requirements
- [x] Sorting should be handled on database side (edit `getProductDataByPrefecture`)
  - Look at the `getProductDataByPopularity` view to see how sorting is done based on Bookmark count (an issue is open to change this to Like count)
- [x] Primary order of products:
  1. Available now but ending soonest
  - ```javascript
    { 'start_date': '2023-05-30', 'end_date': '2023-06-25' }
    ```
  3. Available now but ending later
  - ```javascript
    { 'start_date': '2023-05-30', 'end_date': '2023-08-25' }
    ```
  5. Not yet available with no end date
  - ```javascript
    { 'start_date': '2023-07-30', 'end_date': null }
    ```
  7. Most recently available with no end date
  - ```javascript
    { 'start_date': '2023-06-20', 'end_date': null }
    ```
  9. Lest recently available with no end date 
  - ```javascript
    { 'start_date': '2023-02-30', 'end_date': null }
    ```
  11. No longer available
  - ```javascript
    { 'start_date': '2023-02-30', 'end_date': '2023-05-25' }
    ```
  13. No availability info
  - ```javascript
    { 'start_date': null, 'end_date': null }
    ```

**Comment by SirrorsMoore1975** [comment]
Today date: 2023-06-21
