### ISSUE TITLE
Prevent major UI leakage in Desktop view

### ISSUE THREAD

**Issue by kappanjoe** [OriOri-CCP7/oriori#155]
- [x] Without using CSS Media selectors...
- [x] Prevent the UI from looking awful in a desktop browser window
- [x] Places to pay special attention:
  - [x] App class dimensions (for example, maybe set: `max-width: 800px;`)
  - [x] Navbar dimensions

**Comment by ikuno815** [comment]
- Line the product cards in two columns when users use screens more than medium size.
- Define the specific width size(250px) of usernameInput and dropdownMenu in Settings.
