### ISSUE TITLE
[Suggestion] Create Setting table for user to store user setting

### ISSUE THREAD

**Issue by SirrorsMoore1975** [OriOri-CCP7/oriori#177]
Testing out the issue feature in github: 

Hi Oriori team:

I notice that your app has a setting section and some future plans for expending user settings, but reading between the codes I have not been able to see any database or table that the app can store its user data to. May I suggest your team to add a setting table to store user setting data?

For example, a field for storing user's 'left or right menu bar for each product' preference?

Best Wishes
From an insane fan of oriori

**Comment by kappanjoe** [comment]
Thanks Chadwick! 😂 

It seems I didn't configure the Issue template properly somehow so I'll see if I can fix that in another issue.

About the Settings table, I think this is maybe a good idea for the future! Right now we only have two settings that are directly owned by each User record (location, and now left/right-handedness) so there doesn't seem to be a need for a separate table. I'll close this issue for now but I'll keep a note in the Oriori Admin project!
