### ISSUE TITLE
Write unit tests for Header component

### ISSUE THREAD

**Issue by kappanjoe** [OriOri-CCP7/oriori#183]
## Acceptance Criteria:
Please write tests using React Testing Library to ensure the following functionality:
- [x] Component renders `mainText` prop as `<h1>` element when provided
- [ ] Component does not render `<h1>` element when `mainText` is not provided
- [x] Component renders `secondaryText` prop as `<h2>` element when provided
- [x] Component does not render `<h2>` element when `secondaryText` is not provided

The test filepath should follow this location/format:
`client/src/components/__tests__/ComponentName.test.tsx`

## About Writing Tests
- Please note that examples may use JavaScript, but we are using TypeScript.
- Remember: **S**etup, **E**xecute, **A**ssert, **T**eardown
  - (_OR:_) _**A**rrange, **A**ct, **A**ssert_
- [React Testing Library Examples](https://testing-library.com/docs/react-testing-library/example-intro)
- [React Testing Library Cheatsheet](https://testing-library.com/docs/react-testing-library/cheatsheet)

**Comment by nikobatzi1990** [comment]
Is it necessary to check for the `mainText`'s absence when it's not an optional prop? I think attempting to use `Header` without setting `mainText` would throw a TypeScript error.
