### ISSUE TITLE
CSS Styling: Input/Dropdown components

### ISSUE THREAD

**Issue by kappanjoe** [OriOri-CCP7/oriori#61]
- [ ] Basic CSS layout for:
  - [x] Input component
  - [ ] Dropdown menu component
  - [x] Button component

**Comment by SirrorsMoore1975** [comment]
A rework is needed if we are going to create a fancy looking dropdown menu. Browser seems to have control and ignore any changes if we are using pure html tag for select option type of dropdown menu.
